name: Playground

on:
  push:

jobs:
  playground:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.REGION }}

      - uses: licenseware/unique-elbv2-listener-rule-priority@meysam/sort-result-and-customize-delimiter
        name: Get unique listerner rule priority
        id: elb-priority
        with:
          listener-arn: ${{ secrets.LOAD_BALANCER_LISTENER_ARN }}
          sorted: true
          delimiter: " "
          count: 3

      - name: Get load balancer priorities
        run: |
          export PRIORITIES=$(echo ${{ steps.elb-priority.outputs.priorities }})

          cat << EOF >> $GITHUB_ENV
          MYAPP_LB_PR=$(echo $PRIORITIES | awk '{print $1}')
          YOURAPP_LB_PR=$(echo $PRIORITIES | awk '{print $2}')
          HISAPP_LB_PR=$(echo $PRIORITIES | awk '{print $3}')
          EOF

      - name: Test it out
        run: |
          echo ${{ env.MYAPP_LB_PR }}
          echo ${{ env.YOURAPP_LB_PR }}
          echo ${{ env.HISAPP_LB_PR }}
